Lint/UselessAccessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  MinSize: 3

Style/WordArray:
  MinSize: 3
